services:
  - type: web
    name: redirect-app
    runtime: static
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
